# Generated by Django 5.0.7 on 2025-12-02 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='encrypted_files/', verbose_name='Encrypted File')),
                ('owner_email', models.EmailField(max_length=254, verbose_name='Owner Email')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('deleted', 'Deleted')], max_length=50, verbose_name='File Status')),
            ],
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254, verbose_name='Recipient Email')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50, verbose_name='Email Status')),
                ('encrypted_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='util.encryptedfile', verbose_name='Associated Encrypted File')),
            ],
        ),
    ]
